services:
  cellprofiler:
    image: community.wave.seqera.io/library/cellprofiler:4.2.8--aff0a99749304a7f
    platform: linux/amd64
    container_name: pcpip-cellprofiler
    volumes:
      - ./pipelines:/app/pipelines:ro
      - ./plugins:/app/plugins:ro
      - ./scripts:/app/scripts:ro
      - ./data:/app/data:rw
    working_dir: /app/scripts
    entrypoint: []
    command: ["bash", "run_pcpip.sh"]
    environment:
      - DISPLAY=
      - JAVA_HOME=/opt/conda
      - LD_LIBRARY_PATH=/opt/conda/lib/jvm/lib/server:/opt/conda/lib
      - PIPELINE_STEP=${PIPELINE_STEP}
      - CROP_PERCENT=${CROP_PERCENT}
      - JAVA_OPTS=-Xmx2G
      - JAVA_HOME=/opt/conda
      - LD_LIBRARY_PATH=/opt/conda/lib/jvm/lib/server:/opt/conda/lib
    stdin_open: true
    tty: true

  cellprofiler-shell:
    image: community.wave.seqera.io/library/cellprofiler:4.2.8--aff0a99749304a7f
    platform: linux/amd64
    container_name: pcpip-cellprofiler-shell
    volumes:
      - ./pipelines:/app/pipelines:ro
      - ./plugins:/app/plugins:ro
      - ./scripts:/app/scripts:ro
      - ./data:/app/data:rw
    working_dir: /app
    entrypoint: []
    command: ["bash"]
    environment:
      - DISPLAY=
      - JAVA_HOME=/opt/conda
      - LD_LIBRARY_PATH=/opt/conda/lib/jvm/lib/server:/opt/conda/lib
      - CROP_PERCENT=${CROP_PERCENT}
    stdin_open: true
    tty: true
    profiles:
      - interactive

  fiji:
    image: fiji/fiji:latest
    platform: linux/amd64
    container_name: pcpip-fiji
    volumes:
      - ./scripts:/app/scripts:ro
      - ./data:/app/data:rw
    working_dir: /app/scripts
    entrypoint: []
    command: ["bash", "run_pcpip.sh"]
    environment:
      - DISPLAY=
      - JAVA_HOME=/opt/conda
      - LD_LIBRARY_PATH=/opt/conda/lib/jvm/lib/server:/opt/conda/lib
      - PIPELINE_STEP=${PIPELINE_STEP}
      - CROP_PERCENT=${CROP_PERCENT}
    stdin_open: true
    tty: true

  fiji-shell:
    image: fiji/fiji:latest
    platform: linux/amd64
    container_name: pcpip-fiji-shell
    volumes:
      - ./scripts:/app/scripts:ro
      - ./data:/app/data:rw
    working_dir: /app
    entrypoint: []
    command: ["bash"]
    environment:
      - DISPLAY=
      - JAVA_HOME=/opt/conda
      - LD_LIBRARY_PATH=/opt/conda/lib/jvm/lib/server:/opt/conda/lib
      - CROP_PERCENT=${CROP_PERCENT}
    stdin_open: true
    tty: true
    profiles:
      - interactive

  # Minimal QC service with Pixi
  qc:
    image: ghcr.io/prefix-dev/pixi:latest
    platform: linux/amd64
    container_name: pcpip-qc
    volumes:
      - ./scripts:/app/scripts:ro
      - ./data:/app/data:rw
    working_dir: /app/scripts
    entrypoint: []
    command: ["bash", "run_pcpip.sh"]
    environment:
      - PYTHONUNBUFFERED=1
      - PIPELINE_STEP=${PIPELINE_STEP}
    stdin_open: true
    tty: true

  qc-shell:
    image: ghcr.io/prefix-dev/pixi:latest
    platform: linux/amd64
    container_name: pcpip-qc-shell
    volumes:
      - ./scripts:/app/scripts:ro
      - ./data:/app/data:rw
    working_dir: /app
    entrypoint: []
    command: ["bash"]
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    profiles:
      - interactive
